apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: ghcr.io/invitexbot/invitex
  newName: ghcr.io/invitexbot/invitex
  newTag: sha-e581d4c
