apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
images:
- name: ghcr.io/invitexbot/shardex
  newName: ghcr.io/invitexbot/shardex
  newTag: sha-f4dd0b1
