apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
images:
- name: ghcr.io/invitexbot/bannex
  newName: ghcr.io/invitexbot/bannex
  newTag: sha-da8db99
